server:
  port: 8080
  address: 0.0.0.
spring:
  datasource:
    url: "jdbc:h2:mem:premier_league_web_scraper"
    username: "sa"
    password:
    driver-class-name: "org.h2.Driver"
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
  h2:
    console:
      enabled: true
      path: "/h2-console"

#Enviroment variables
premier:
  league:
    url: ${PREMIER_LEAGUE_URL:https://www.premierleague.com/}